{
    "componentChunkName": "component---src-templates-challenges-odin-show-tsx",
    "path": "/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/implement-exception-handling-in-c-sharp-console-applications",
    "result": {"data":{"challengeNode":{"challenge":{"videoId":null,"videoLocaleIds":null,"bilibiliIds":null,"title":"Implement Exception Handling in C# Console Applications","description":"<section id=\"description\">\n<p>This challenge will be partially completed on the Microsoft Learn platform. Follow these instructions to complete the challenge:</p>\n<ol>\n<li>Go to <a href=\"https://learn.microsoft.com/training/modules/implement-exception-handling-c-sharp/\" target=\"_blank\" rel=\"noreferrer\">https://learn.microsoft.com/training/modules/implement-exception-handling-c-sharp/</a> and complete all the tasks for the \"Implement Exception Handling in C# Console Applications\" module. This is <strong>required</strong> to earn the \"Debug C# Console Applications\" trophy on Microsoft Learn, and qualify for the certification exam.</li>\n<li>When you are finished, come back and correctly answer the question below.</li>\n</ol>\n</section>","challengeType":19,"helpCategory":"C-Sharp","superBlock":"foundational-c-sharp-with-microsoft","block":"debug-c-sharp-console-applications","fields":{"slug":"/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/implement-exception-handling-in-c-sharp-console-applications","blockName":"debug-c-sharp-console-applications","tests":[]},"question":{"text":"<p>When is an <code>ArrayTypeMismatchException</code> exception thrown?</p>","answers":[{"answer":"<p>An <code>ArrayTypeMismatchException</code> exception is thrown when an attempt is made to store a value of one type in an array of another type.</p>","feedback":null},{"answer":"<p>An <code>ArrayTypeMismatchException</code> exception is thrown when attempting to access a member on a type whose value is null.</p>","feedback":null},{"answer":"<p>An <code>ArrayTypeMismatchException</code> exception is thrown when an attempt is made to index an array outside the bounds of the array.</p>","feedback":null}],"solution":1},"scene":null,"translationPending":false,"assignments":["<p>Complete the <a href=\"https://learn.microsoft.com/training/modules/implement-exception-handling-c-sharp/\" target=\"_blank\" rel=\"noreferrer\">Implement Exception Handling in C# Console Applications</a> module on Microsoft Learn. Then, answer the question below.</p>"],"audioPath":null}}},"pageContext":{"challengeMeta":{"blockHashSlug":"/learn/foundational-c-sharp-with-microsoft/#debug-c-sharp-console-applications","dashedName":"implement-exception-handling-in-c-sharp-console-applications","certification":"foundational-c-sharp-with-microsoft","disableLoopProtectTests":false,"disableLoopProtectPreview":false,"superBlock":"foundational-c-sharp-with-microsoft","block":"debug-c-sharp-console-applications","isFirstStep":false,"template":null,"required":[],"nextBlock":"debug-c-sharp-console-applications","nextChallengePath":"/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/create-and-throw-exceptions-in-c-sharp-console-applications","prevChallengePath":"/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/implement-the-visual-studio-code-debugging-tools-for-c-sharp","id":"647e22a08acb466c97ccbef5"},"projectPreview":{"showProjectPreview":false,"challengeData":{"challengeType":18,"challengeFiles":[]}},"slug":"/learn/foundational-c-sharp-with-microsoft/debug-c-sharp-console-applications/implement-exception-handling-in-c-sharp-console-applications"}},
    "staticQueryHashes": ["1800977889","4268002518"]}